[book]
authors = ["{{GROUP_NAME}} Members"]
language = "en"
multilingual = false
src = "."
title = "{{GROUP_NAME}} {{GROUP_TYPE}} Group"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/{{GROUP_SLUG}}"
